name: Publish Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set-Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Documentation
        run: |
          cd docs && sphinx-apidoc -o ./source ../src && make html
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply doc updates
          
      - name: Push Doc Files (HTML) to Service Repo
        uses: nkoppel/push-files-to-another-repository@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.MY_TOKEN }}
        with:
          source-files: 'docs/build/html/*'
          destination-username: 'tim-corley'
          destination-repository: 'foobarService'
          destination-branch: 'main'
          destination-directory: 'content/'
          commit-email: '<>'
