name: Copy & Push

on:
  push:
    branches:
      - master

jobs:
  run_job:
    runs-on: ubuntu-latest

    steps:
      - name: Push Files to Other Repo
        uses: nkoppel/push-files-to-another-repository@v1.1.1

        env:
          API_TOKEN_GITHUB: ${{ secrets.MY_TOKEN }}
        with:
          source-files: 'docs/'
          destination-username: 'tim-corley'
          destination-repository: 'foobarService'
          destination-branch: 'main'
          destination-directory: 'content/'
          commit-email: '<>'
