name: Trigger Job on Push

on:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch Job
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MY_TOKEN }}
          repository: tim-corley/foobarService
          event-type: trigger-job
